baseURL = "https://sp4rrow.net"
languageCode = "en-us"
title = "SP4RROW"
theme = "smol"

[params]
    subtitle = "Modest angel, far from home."
    dateFmt = "02.01.2006"

[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2

  [[menu.main]]
        name = "About"
        url = "/about"
        weight = 4

  [[menu.footer]]
        name = "Github"
        url = "https://github.com/alissa-maria"
        weight = 1
