baseURL = "https://sp4rrow.net"
languageCode = "en-us"
title = "SP4RROW"
theme = "hugo-bearblog"

[params]
    subtitle = "The atmosphere hums with power."
    dateFmt = "02.01.2006"

[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        name = "About"
        url = "/about"
        weight = 4

  [[menu.footer]]
        name = "Github"
        url = "https://github.com/alissa-maria"
        weight = 1

[markup]
  [markup.highlight]
    noClasses = false
